"""tree_metrics.py
====================

Utility helpers to study batches of mutation graphs generated by
``phylogeny_list.PhylogenyList``.  Each tree dictionary exposes ``tree_id``,
``X`` (node types), ``E`` (adjacency matrix of edge types), and ``L`` (labels).

This module focuses on three tasks:

* Compute per-tree summary metrics and aggregate means across a batch.
* Visualise the distributions of those metrics via Matplotlib histograms.
* Validate that each graph obeys our mutation-graph rules and report a
  pass-rate percentage.

Usage example (runs the bundled sample batch and prints a report):

    >>> from tree_metrics import run_sample_analysis
    >>> analysis = run_sample_analysis()
    Average metrics:
      average_total_nodes: ...
      ...
    Validity summary:
      Passed: ...
      Failed: ...
      Pass percentage: ...

The code prefers clarity over cleverness and keeps the logic modular so that
callers can mix-and-match the helpers when running analyses or notebooks.
"""

from __future__ import annotations

import pickle
from dataclasses import dataclass
from typing import Any, Dict, Iterable, List, Mapping, MutableMapping, Optional, Sequence, Tuple

import matplotlib.pyplot as plt
import numpy as np


# ---------------------------------------------------------------------------
# Data containers
# ---------------------------------------------------------------------------


@dataclass
class ValidityResult:
    """Hold the outcome of the mutation-graph validity checks.

    Attributes:
        is_valid: ``True`` when every rule passes.
        has_cycle: ``True`` if the clone-only subgraph contains a cycle.
        root_has_single_clone_neighbor: ``True`` when the root has exactly one
            clone neighbour connected via a clone edge.
        clone_edge_types_valid: ``True`` when clone edges (type ``1``) only
            connect root/clone nodes.
        mutation_edge_types_valid: ``True`` when mutation edges (type ``2``)
            only connect clone nodes to mutation nodes.
    """

    is_valid: bool
    has_cycle: bool
    root_has_single_clone_neighbor: bool
    clone_edge_types_valid: bool
    mutation_edge_types_valid: bool


@dataclass
class TreeMetrics:
    """Per-tree statistics derived from the adjacency matrix and node types."""

    tree_id: str
    total_nodes: int
    root_nodes: int
    clone_nodes: int
    mutation_nodes: int
    total_edges: int
    clone_edges: int
    mutation_edges: int
    validity: ValidityResult


# ---------------------------------------------------------------------------
# Core metric helpers
# ---------------------------------------------------------------------------


def _to_numpy(tree_dict: Mapping[str, Any]) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Convert raw ``list`` storage back into ``numpy`` arrays.

    The pickle files we consume keep built-in Python containers for
    compatibility, so we normalise them here for downstream vectorised logic.
    """

    node_types = np.asarray(tree_dict["X"], dtype=int)
    adjacency = np.asarray(tree_dict["E"], dtype=int)
    labels = np.asarray(tree_dict.get("L", []), dtype=object)
    return node_types, adjacency, labels


def _count_edges(adjacency: np.ndarray) -> Tuple[int, int, int]:
    """Count total, clone, and mutation edges using the upper-triangle only."""

    # We treat clone and mutation edges as undirected, therefore the adjacency
    # matrix is symmetric.  Counting only the upper triangle avoids double
    # counting while respecting the input contract.
    upper_r, upper_c = np.triu_indices_from(adjacency, k=1)
    upper_values = adjacency[upper_r, upper_c]

    total_edges = int(np.count_nonzero(upper_values))
    clone_edges = int(np.count_nonzero(upper_values == 1))
    mutation_edges = int(np.count_nonzero(upper_values == 2))
    return total_edges, clone_edges, mutation_edges


def _clone_neighbors(adjacency: np.ndarray, node_types: np.ndarray, node_index: int) -> np.ndarray:
    """Return neighbour indices connected via clone edges (type ``1``)."""

    clone_mask = adjacency[node_index] == 1
    neighbours = np.flatnonzero(clone_mask)
    return neighbours


def _has_clone_cycle(adjacency: np.ndarray, node_types: np.ndarray) -> bool:
    """Detect cycles in the undirected clone-only subgraph.

    We restrict the traversal to root/clone nodes (types ``0`` and ``1``) and
    treat edges of type ``1`` as undirected connections.  A depth-first search
    that revisits a node that is not the direct parent reveals a cycle.
    """

    clone_like = np.flatnonzero((node_types == 0) | (node_types == 1))
    if clone_like.size == 0:
        return False

    visited: set[int] = set()

    for start in clone_like:
        if start in visited:
            continue
        stack: List[Tuple[int, int]] = [(start, -1)]
        while stack:
            node, parent = stack.pop()
            if node in visited:
                # Encountering a previously visited node from a different
                # branch signals a cycle.
                if parent != -1:
                    return True
                continue
            visited.add(node)
            neighbours = _clone_neighbors(adjacency, node_types, node)
            for neighbour in neighbours:
                if neighbour == parent:
                    continue
                if neighbour in visited:
                    return True
                stack.append((neighbour, node))

    return False


def _validate_edge_types(adjacency: np.ndarray, node_types: np.ndarray) -> Tuple[bool, bool]:
    """Ensure clone/clone links use clone edges and clone/mutation links use mutation edges."""

    clone_edge_types_valid = True
    mutation_edge_types_valid = True

    node_count = adjacency.shape[0]
    for i in range(node_count):
        for j in range(i + 1, node_count):
            edge_type = adjacency[i, j]
            if edge_type == 0:
                continue

            node_i_type = node_types[i]
            node_j_type = node_types[j]

            if edge_type == 1:
                # Clone edges should only connect the root or clones to other clones.
                if not ((node_i_type in (0, 1)) and (node_j_type in (0, 1))):
                    clone_edge_types_valid = False
            elif edge_type == 2:
                # Mutation edges must bridge clone and mutation nodes.
                valid_pair = ((node_i_type == 1 and node_j_type == 2) or
                              (node_i_type == 2 and node_j_type == 1))
                if not valid_pair:
                    mutation_edge_types_valid = False

    return clone_edge_types_valid, mutation_edge_types_valid


def _check_root_degree(adjacency: np.ndarray, node_types: np.ndarray) -> bool:
    """Confirm the root has exactly one clone neighbour via clone edges."""

    root_indices = np.flatnonzero(node_types == 0)
    if root_indices.size != 1:
        return False

    root_idx = int(root_indices[0])
    neighbours = _clone_neighbors(adjacency, node_types, root_idx)

    # Only count neighbours that are real clone nodes (type ``1``).
    clone_neighbours = [idx for idx in neighbours if node_types[idx] == 1]
    return len(clone_neighbours) == 1 and len(neighbours) == 1


def compute_tree_metrics(tree_dict: Mapping[str, Any]) -> TreeMetrics:
    """Compute the metrics and validity flags for a single tree dictionary."""

    node_types, adjacency, _labels = _to_numpy(tree_dict)

    total_nodes = int(node_types.size)
    root_nodes = int(np.count_nonzero(node_types == 0))
    clone_nodes = int(np.count_nonzero(node_types == 1))
    mutation_nodes = int(np.count_nonzero(node_types == 2))

    total_edges, clone_edges, mutation_edges = _count_edges(adjacency)

    has_cycle = _has_clone_cycle(adjacency, node_types)
    root_degree_valid = _check_root_degree(adjacency, node_types)
    clone_edge_types_valid, mutation_edge_types_valid = _validate_edge_types(adjacency, node_types)

    all_rules_ok = (not has_cycle and root_degree_valid and
                    clone_edge_types_valid and mutation_edge_types_valid)

    validity = ValidityResult(
        is_valid=all_rules_ok,
        has_cycle=has_cycle,
        root_has_single_clone_neighbor=root_degree_valid,
        clone_edge_types_valid=clone_edge_types_valid,
        mutation_edge_types_valid=mutation_edge_types_valid,
    )

    return TreeMetrics(
        tree_id=str(tree_dict.get("tree_id", "unknown")),
        total_nodes=total_nodes,
        root_nodes=root_nodes,
        clone_nodes=clone_nodes,
        mutation_nodes=mutation_nodes,
        total_edges=total_edges,
        clone_edges=clone_edges,
        mutation_edges=mutation_edges,
        validity=validity,
    )


# ---------------------------------------------------------------------------
# Aggregation and histogram helpers
# ---------------------------------------------------------------------------


def aggregate_metrics(metrics: Sequence[TreeMetrics]) -> Dict[str, float]:
    """Return mean values for the requested metric fields."""

    if not metrics:
        return {
            "average_total_nodes": 0.0,
            "average_root_nodes": 0.0,
            "average_clone_nodes": 0.0,
            "average_mutation_nodes": 0.0,
            "average_total_edges": 0.0,
            "average_clone_edges": 0.0,
            "average_mutation_edges": 0.0,
        }

    def mean(values: Iterable[int]) -> float:
        arr = np.fromiter(values, dtype=float)
        return float(arr.mean()) if arr.size else 0.0

    return {
        "average_total_nodes": mean(metric.total_nodes for metric in metrics),
        "average_root_nodes": mean(metric.root_nodes for metric in metrics),
        "average_clone_nodes": mean(metric.clone_nodes for metric in metrics),
        "average_mutation_nodes": mean(metric.mutation_nodes for metric in metrics),
        "average_total_edges": mean(metric.total_edges for metric in metrics),
        "average_clone_edges": mean(metric.clone_edges for metric in metrics),
        "average_mutation_edges": mean(metric.mutation_edges for metric in metrics),
    }


def metric_series(metrics: Sequence[TreeMetrics]) -> Dict[str, List[int]]:
    """Expose raw metric lists so callers can build custom plots if desired."""

    return {
        "total_nodes": [metric.total_nodes for metric in metrics],
        "root_nodes": [metric.root_nodes for metric in metrics],
        "clone_nodes": [metric.clone_nodes for metric in metrics],
        "mutation_nodes": [metric.mutation_nodes for metric in metrics],
        "total_edges": [metric.total_edges for metric in metrics],
        "clone_edges": [metric.clone_edges for metric in metrics],
        "mutation_edges": [metric.mutation_edges for metric in metrics],
    }


def create_histograms(series: Mapping[str, Sequence[int]], bins: str | int = "auto") -> Dict[str, plt.Figure]:
    """Produce a single 2x3 subplot figure with distributions and mean lines.

    The figure contains:
    - Row 1: total_nodes, clone_nodes, mutation_nodes distributions
    - Row 2: total_edges, clone_edges, mutation_edges distributions
    Each subplot includes a horizontal line indicating the mean value.

    The caller takes ownership of the returned figure (e.g., display in a
    notebook or save to disk).  Using a helper keeps the plotting code in one
    place so that styling tweaks stay consistent.
    """

    # Create a single figure with 2x3 subplots
    fig, axes = plt.subplots(2, 3, figsize=(15, 10))

    # Row 1: Node distributions
    node_metrics = [
        ("total_nodes", 0, 0),    # Top-left
        ("clone_nodes", 0, 1),     # Top-middle
        ("mutation_nodes", 0, 2),  # Top-right
    ]

    # Row 2: Edge distributions
    edge_metrics = [
        ("total_edges", 1, 0),     # Bottom-left
        ("clone_edges", 1, 1),      # Bottom-middle
        ("mutation_edges", 1, 2),   # Bottom-right
    ]

    # Plot node distributions (row 1)
    for key, row, col in node_metrics:
        if key not in series:
            axes[row, col].axis("off")
            continue

        values = series[key]
        arr = np.asarray(list(values), dtype=float)
        mean_val = float(np.mean(arr))

        # Apply integer-aligned binning only for clone nodes
        if key == "clone_nodes":
            # For integer data, create bins centered on whole numbers
            # Bins edges are at 0.5, 1.5, 2.5, etc. so bars center on integers
            min_val = int(np.min(arr))
            max_val = int(np.max(arr)) + 1
            bin_edges = np.arange(min_val - 0.5, max_val + 1.5, 1)

            # Create histogram with integer-aligned bins
            axes[row, col].hist(arr, bins=bin_edges, edgecolor="black", align="mid")
            
            # Set integer tick marks on x-axis
            # Show all integers if range is small, otherwise show every 2-3 integers
            tick_range = max_val - min_val
            if tick_range <= 20:
                # Show every integer for small ranges
                axes[row, col].set_xticks(np.arange(min_val, max_val + 1))
            elif tick_range <= 40:
                # Show every 2 integers for medium ranges
                axes[row, col].set_xticks(np.arange(min_val, max_val + 1, 2))
            else:
                # Show every 5 integers for large ranges
                axes[row, col].set_xticks(np.arange(min_val, max_val + 1, 5))
        else:
            # Use default binning for other metrics
            axes[row, col].hist(arr, bins=bins, edgecolor="black")
        
        # Add vertical line at the mean value
        axes[row, col].axvline(mean_val, color="red", linestyle="--", linewidth=2)

        # Set labels and styling
        axes[row, col].set_title(f"Distribution of {key.replace('_', ' ')}")
        axes[row, col].set_xlabel(key.replace('_', ' '))
        axes[row, col].set_ylabel("count")
        axes[row, col].grid(True, linestyle=":", alpha=0.4)

    # Plot edge distributions (row 2)
    for key, row, col in edge_metrics:
        if key not in series:
            axes[row, col].axis("off")
            continue

        values = series[key]
        arr = np.asarray(list(values), dtype=float)
        mean_val = float(np.mean(arr))

        # Apply integer-aligned binning only for clone edges
        if key == "clone_edges":
            # For integer data, create bins centered on whole numbers
            # Bins edges are at 0.5, 1.5, 2.5, etc. so bars center on integers
            min_val = int(np.min(arr))
            max_val = int(np.max(arr)) + 1
            bin_edges = np.arange(min_val - 0.5, max_val + 1.5, 1)

            # Create histogram with integer-aligned bins
            axes[row, col].hist(arr, bins=bin_edges, edgecolor="black", align="mid")
            
            # Set integer tick marks on x-axis
            # Show all integers if range is small, otherwise show every 2-3 integers
            tick_range = max_val - min_val
            if tick_range <= 20:
                # Show every integer for small ranges
                axes[row, col].set_xticks(np.arange(min_val, max_val + 1))
            elif tick_range <= 40:
                # Show every 2 integers for medium ranges
                axes[row, col].set_xticks(np.arange(min_val, max_val + 1, 2))
            else:
                # Show every 5 integers for large ranges
                axes[row, col].set_xticks(np.arange(min_val, max_val + 1, 5))
        else:
            # Use default binning for other metrics
            axes[row, col].hist(arr, bins=bins, edgecolor="black")
        
        # Add vertical line at the mean value
        axes[row, col].axvline(mean_val, color="red", linestyle="--", linewidth=2)

        # Set labels and styling
        axes[row, col].set_title(f"Distribution of {key.replace('_', ' ')}")
        axes[row, col].set_xlabel(key.replace('_', ' '))
        axes[row, col].set_ylabel("count")
        axes[row, col].grid(True, linestyle=":", alpha=0.4)

    plt.tight_layout()  # Adjust spacing between subplots

    # Return dict with single figure for compatibility
    return {"all_metrics": fig}


def validity_summary(metrics: Sequence[TreeMetrics]) -> Dict[str, Any]:
    """Summarise validity outcomes, including the pass percentage."""

    if not metrics:
        return {
            "passed": 0,
            "failed": 0,
            "pass_percentage": 0.0,
        }

    passed = sum(1 for metric in metrics if metric.validity.is_valid)
    failed = len(metrics) - passed
    pass_percentage = (passed / len(metrics)) * 100.0
    return {
        "passed": passed,
        "failed": failed,
        "pass_percentage": pass_percentage,
    }


# ---------------------------------------------------------------------------
# Batch analysis convenience wrapper
# ---------------------------------------------------------------------------


DEFAULT_SAMPLE_BATCH = "/Users/siddharthsabata/dev/research/sistem-transform/dataset/combined_experiments.pkl"


def analyse_tree_dicts(tree_dicts: Sequence[Mapping[str, Any]], bins: str | int = "auto") -> Dict[str, Any]:
    """Run the full analysis pipeline on an in-memory list of tree dictionaries."""

    metrics = [compute_tree_metrics(tree) for tree in tree_dicts]
    averages = aggregate_metrics(metrics)
    series = metric_series(metrics)
    figures = create_histograms(series, bins=bins) if metrics else {}
    validity = validity_summary(metrics)

    return {
        "metrics": metrics,
        "averages": averages,
        "histograms": figures,
        "validity": validity,
    }


def run_sample_analysis(batch_path: str = DEFAULT_SAMPLE_BATCH, bins: str | int = "auto") -> Dict[str, Any]:
    """Load a pickle batch, analyse it, and print a short textual summary."""

    with open(batch_path, "rb") as handle:
        tree_dicts = pickle.load(handle)

    analysis = analyse_tree_dicts(tree_dicts, bins=bins)

    averages = analysis["averages"]
    validity = analysis["validity"]

    print("Average metrics:")
    for key, value in averages.items():
        print(f"  {key}: {value:.2f}")

    print("\nValidity summary:")
    print(f"  Passed: {validity['passed']}")
    print(f"  Failed: {validity['failed']}")
    print(f"  Pass percentage: {validity['pass_percentage']:.2f}%")

    return analysis


__all__ = [
    "TreeMetrics",
    "ValidityResult",
    "aggregate_metrics",
    "analyse_tree_dicts",
    "compute_tree_metrics",
    "create_histograms",
    "metric_series",
    "run_sample_analysis",
    "validity_summary",
]


def main() -> None:
    """Run the sample batch analysis and display histogram windows if present."""

    analysis = run_sample_analysis()

    # The histogram figures are returned rather than saved so interactive users
    # can decide how to handle them.  When this script runs directly we show
    # them via Matplotlib's default backend.
    if analysis["histograms"]:
        print("\nShowing histogram windows...")
        plt.show()


if __name__ == "__main__":
    main()


